// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dawsonfi/gobrals/internal/address"
)

// Injectors from wire.go:

func InitializeAddressHandler(dbPath string) (*address.Handler, error) {
	jsonZipDatabaseLoader := address.NewJsonDatabaseLoader(dbPath)
	service, err := address.NewService(jsonZipDatabaseLoader)
	if err != nil {
		return nil, err
	}
	handler := address.NewHandler(service)
	return handler, nil
}
